dsd

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -14,25 +14,31 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v2
 
-      # List files in the project directory
+      # List files in the project directory to ensure VizzanoERP exists
       - name: List files in the project directory
-        run: ls -la ./VizzanoERP
+        run: ls -la
 
       # Create a tar archive of the files
       - name: Create tar archive
         run: |
-          tar -cvf /tmp/project_archive.tar ./VizzanoERP/*
+          # Ensure the correct directory is targeted
+          if [ -d "./VizzanoERP" ]; then
+            tar -cvf /tmp/project_archive.tar ./VizzanoERP/*
+          else
+            echo "Directory ./VizzanoERP not found."
+            exit 1
+          fi
 
       # Upload to FTP server using appleboy/ftp-action
       - name: Upload to FTP server
         uses: SamKirkland/FTP-Deploy-Action@4.0.0
         with:
-          host: ${{ secrets.FTP_SERVER }}        # FTP server host
-          username: ${{ secrets.FTP_USERNAME }}  # FTP username
-          password: ${{ secrets.FTP_PASSWORD }}  # FTP password
-          port: 22                              # FTP port (usually 22 for SFTP)
-          source: /tmp/project_archive.tar      # Path to the tar archive
-          target: "/home/ftpuser/destination_folder"  # FTP target directory
+          host: ${{ secrets.FTP_HOST }}
+          username: ${{ secrets.FTP_USERNAME }}
+          password: ${{ secrets.FTP_PASSWORD }}
+          port: 22
+          source: /tmp/project_archive.tar
+          target: "/home/ftpuser/destination_folder"
           timeout: 30s
           command_timeout: 10m
           use_insecure_cipher: false
