asas

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -10,34 +10,46 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-      # Checkout the code from the repository
+      # Repozitoriyani olish
       - name: Checkout code
         uses: actions/checkout@v2
 
-      # List files in the project directory to ensure VizzanoERP exists
-      - name: List files in the project directory
-        run: ls -la
-
-      # Create a tar archive of the files
-      - name: Create tar archive
+      # Barcha fayllarni ko'rsatish
+      - name: List all files
         run: |
-          # Ensure the correct directory is targeted
+          echo "Listing all files in the current directory"
+          ls -la
+
+      # VizzanoERP papkasini tekshirish
+      - name: Check if VizzanoERP exists
+        run: |
           if [ -d "./VizzanoERP" ]; then
-            tar -cvf /tmp/project_archive.tar ./VizzanoERP/*
+            echo "VizzanoERP directory exists!"
           else
-            echo "Directory ../VizzanoERP not found."
+            echo "VizzanoERP directory does not exist!"
             exit 1
           fi
 
-      # Upload to FTP server using appleboy/ftp-action
+      # Tar arxivini yaratish
+      - name: Create tar archive
+        run: |
+          if [ -d "./VizzanoERP" ]; then
+            echo "Creating archive from VizzanoERP..."
+            tar -cvf /tmp/VizzanoERP.tar ./VizzanoERP/*
+          else
+            echo "VizzanoERP directory not found."
+            exit 1
+          fi
+
+      # FTPga yuklash
       - name: Upload to FTP server
-        uses: SamKirkland/FTP-Deploy-Action@4.0.0
+        uses: appleboy/ftp-action@v1.2.0
         with:
-          host: ${{ secrets.FTP_HOST }}
+          host: ${{ secrets.FTP_SERVER }}
           username: ${{ secrets.FTP_USERNAME }}
           password: ${{ secrets.FTP_PASSWORD }}
           port: 22
-          source: /tmp/project_archive.tar
+          source: /tmp/VizzanoERP.tar
           target: "/home/ftpuser/destination_folder"
           timeout: 30s
           command_timeout: 10m
@@ -46,4 +58,3 @@ jobs:
           debug: true
           strip_components: 0
           overwrite: false
-          server: ''
